Parse negative number constant in ssralg
Before this commit

```Coq
From mathcomp Require Import ssralg.
Local Open Scope ring_scope.

Check -3.
```

was failing with

Error: Cannot interpret this number as a value of type Idummy_placeholder

one needed to import ssrint to get

```Coq
From mathcomp Require Import ssralg ssrint.
Local Open Scope ring_scope.

Check -3.  (* (-3)%:~R *)
```

Now we have

```Coq
From mathcomp Require Import ssralg.
Local Open Scope ring_scope.

Check -3.  (* - (3%:R) *)
```

which is not exactly the same (we don't have `intmul` (notation
`%:~R`) in ssralg) but is convertible.